### ISSUE TITLE
Grabber help pls

### ISSUE THREAD

**Issue by Programmer1603** [TheC0mpany/Discord-Friend-Mass-DM#1]
Hello, i was trying to integrate a simple token grabber into this script so i wont have to get my own token everytime trough the browser. Somehow i cant get it to work properly..... Could you pls help me and provide an example with grabber included? I already tried with variables, but i guess i am not able to programm it on my own. Thank you very much and have a nice day!
Here are my Discord and Telegram: 
Terminatoror#7427
https://t.me/Terminatororor

**Comment by TheC0mpany** [comment]
Sry its not issue about script
